name: Test Deploy to environments

on: 
  workflow_dispatch:
    inputs:
      name:
        description: The target name
        required: true
        default: bob

jobs:
  deploy_dev:
    runs-on: ubuntu_latest
    environment: dev
    steps:
      - shell: bash
        run: echo "Hello ${{ secrets.GREETING }}, ${{ github.events.inputs.name }}"

  deploy_prod:
    needs: deploy_dev
    runs-on: ubuntu_latest
    environment: prod
    steps:
      - shell: bash
        run: echo "Hello ${{ secrets.GREETING }}, ${{ github.events.inputs.name }}"
  